### ISSUE TITLE
Crashes on Initialization, not sure why

### ISSUE THREAD

**Issue by uhhhhhhhhhhhhhhhhhhhhhh** [EurekaEffect/banana-plus-crack#6]
Description: Initializing game

java.lang.NoClassDefFoundError: club/minnced/discord/rpc/DiscordRichPresence
	at bplusdevelopment.addons.modules.BDiscordPresence.<clinit>(BDiscordPresence.java:51)
	at bplusdevelopment.utils.Loading.loading(Loading.java:18)
	at bplusdevelopment.addons.AddModule.onInitialize(AddModule.java:26)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:97)
	at net.minecraft.class_310.handler$zmm005$onInit(class_310.java:8025)
	at net.minecraft.class_310.<init>(class_310.java:637)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: club.minnced.discord.rpc.DiscordRichPresence
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at bplusdevelopment.addons.modules.BDiscordPresence.<clinit>(BDiscordPresence.java:51)
	at bplusdevelopment.utils.Loading.loading(Loading.java:18)
	at bplusdevelopment.addons.AddModule.onInitialize(AddModule.java:26)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:97)
	at net.minecraft.class_310.handler$zmm005$onInit(class_310.java:8025)
	at net.minecraft.class_310.<init>(class_310.java:637)
 
Note that i have no coding knowledge 
i have used google google didnt help

**Comment by deeraj12345** [comment]
same i need help to
